name: Deploy Preview Audit
on: pull_request
jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install & Build
        run: |
          yarn install
          yarn deploy
      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'minimalwebassets'
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/backgrounds/
            ${{ steps.netlify.outputs.url }}/templates/
            ${{ steps.netlify.outputs.url }}/templates/yoga/
            ${{ steps.netlify.outputs.url }}/templates/party/
          configPath: "./.lighthouserc.json"
          uploadArtifacts: true